[package]
name = "two_stroke"
version = "0.1.0"
authors = ["Jon Moroney <darakian@gmail.com>"]

[dependencies]
crossbeam-channel = "0.1"
sdl2 = "0.31"

[dependencies.sdl2]
version = ...
default-features = false
features = ["gfx", "mixer"]
